### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ABCCASa** [HjalteTagmose/AsyncEvent#1]
Hello developer, I found several bugs while using your plugin:

Bug1
if I set method back to None, I will get a NullReferenceException immediately
![image](https://github.com/HjalteTagmose/AsyncEvent/assets/144005707/c2ef3d95-85e5-454e-8846-098f320b3fca)

Bug2 if I directy set GameObject to None but do not remove this element, the previous method will still be executed
![image](https://github.com/HjalteTagmose/AsyncEvent/assets/144005707/6f671f40-3751-416d-b338-cdf1d8f7ab91)

**Comment by HjalteTagmose** [comment]
Hi! Thanks for the bug report. I don't know how I didn't catch those, haha. Anyway, I've pushed a fix for both now! 
Update will be on Asset Store in a couple days once Unity accepts the change.
